### ISSUE TITLE
Don't build with serde support and `no_std`

### ISSUE THREAD

**Issue by nathanielsimard** [starkat99/half-rs#84] opened 2023-03-22 21:54 UTC
I'm not able to build `half` when I use it with `no_std` and serde support.

```bash
   Compiling half v2.2.1
error[E0599]: no method named `to_string` found for reference `&bf16` in the current scope
   --> /home/nathaniel/.cargo/registry/src/github.com-1ecc6299db9ec823/half-2.2.1/src/bfloat.rs:697:40
    |
697 |         serializer.serialize_str(&self.to_string())
    |                                        ^^^^^^^^^ method not found in `&bf16`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use crate::alloc::string::ToString;
```

I use the following configuration `half = {version = "2", features = ["alloc", "num-traits", "serde"], default-features = false}`

I believe the fix should be easy, since it's just a missing import with those specific feature flags.

**Comment by starkat99** [comment] 2023-03-28 05:16
Duplicate of #79

**Closed by starkat99** 2023-03-28 05:16 UTC
Labels: bug, duplicate

**Comment by antimora** [comment] 2023-04-15 15:19
@starkat99 Thank you for fixing the issue. Could you please release the fix with a minor version? We are want to include a new feature for our upcoming release of [Burn](https://github.com/burn-rs/burn)
